"""empty message

Revision ID: 1f03af7ad194
Revises: 
Create Date: 2022-04-28 19:14:45.308659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f03af7ad194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room_ban')
    op.drop_table('mute_user')
    op.drop_table('sessions')
    op.drop_table('complaint')
    op.drop_table('ban_user')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=32), nullable=False),
    sa.Column('text', sa.VARCHAR(length=2500), nullable=False),
    sa.Column('room', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ban_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=32), nullable=False),
    sa.Column('ban_time', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=32), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=256), nullable=True),
    sa.Column('agreed_status', sa.BOOLEAN(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('mute_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=32), nullable=False),
    sa.Column('mute_time', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_ban',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login', sa.VARCHAR(length=32), nullable=False),
    sa.Column('room', sa.VARCHAR(length=32), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ban_end_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('warn', sa.INTEGER(), nullable=True),
    sa.Column('admin_status', sa.BOOLEAN(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
